let stops = [
  "Student Activities & Athletics Center",
  "Merced Mall Target",
  "Amtrak Station",
  "Rite Aid/Walgreens on G St.",
  "\"R\" Street Village Apts.",
  "Bellevue Ranch on Arrow Wood Dr.",
  "Buena Vista Dr.",
  "Castle Air Park",
  "Compass Pointe Apts(Bus stop on Pacific Dr. in front)",
  "El Portal Plaza & \"G\" Street (Bus Stop On \"G\")",
  "El Redondo Dr. (Across from Jenner Dr.)",
  "Emigrant Pass at Scholars Lane",
  "G St. & W. Alexander Ave. (Bus Stop On \"G\" by Gas Station)",
  "Granville Apartments",
  "Ironstone Dr.",
  "K St. Between 18th & 19th (The Bus Stop)",
  "M Street Village Apartments",
  "Meadows Ave & Olivewood Dr. (Food Maxx)",
  "Merced College The Bus Terminal",
  "Mercy Hospital/Tri-College",
  "Moraga Subdivision",
  "R Street Village Apartments",
  "Starbucks/Promenade Center",
  "Tri-College/Mercy (Bus stop On \"G\" Next To Tri College)",
  "University Surgery Center",
  "Villages Apts. \"M\" Street",
  "Walmart on Loughborough",
  "Yosemite & Cordova (Physicians Care)"
]